routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/readerajaxfollow','FollowerController@ajaxfollow');
Route::get('/readerajaxunfollow','FollowerController@ajaxunfollow');
Route::post('/savetime','UserController@saveTime');
Route::get('ajaxfollow','FollowerController@ajaxfollow');
Route::get('ajaxunfollow','FollowerController@ajaxunfollow');
Route::get('users-search','UserController@search');
Route::resource('groups','GroupController');
Route::get('blogs/{cat}','BlogController@view_by_category');
Route::get('followers/{username}','UserController@followers');

Route::post('comment-reply','CommentController@reply');
Route::resource('comment','CommentController');
Route::post('/payment/process', 'PaymentController@process')->name('payment.process');
Route::get('all-notification','FollowerController@all_notifications');
Route::get('readNotification','FollowerController@readNotification');

Route::get('follow/{user_id}','FollowerController@add');
Route::get('unfollow/{user_id}','FollowerController@unfollow');

Route::get('/callback','ApiController@getData')
;
Route::get('blog-search','BlogController@search');

Route::post('add-rating','FollowerController@add_rating');

Route::get('/AuthCallback','ApiController@grantAccess');

Route::get('/redirect', function () {
    $query = http_build_query([
        'client_id' => '4',
        'redirect_uri' => 'http://africanfreelancers.net/AuthCallback',
        'response_type' => 'code',
        'scope' => '*',
    ]);

    return redirect('https://www.opendarasa.com/oauth/authorize?'.$query);
});
Route::get('get-talents','ApiController@getTalents');
Route::get('services',function(){
  return view('services');
});
Route::get('language/{lang}','HomeController@changeLanguage');
Route::post('add_skills','UserController@addSkills');
Route::get('publishBlog/{slug}','HomeController@publishBlog');
Route::get('publishWork/{slug}','HomeController@publishWork');
Route::get('unpublishWork/{slug}','HomeController@unpublishWork');
Route::get('unpublishBlog/{slug}','HomeController@unpublishBlog');
Route::post('profile-type','HomeController@saveprofile');
/*Route::get('portofolio',function(){
  return view('portofolio');
});
Route::get('blog',function(){
   return view('blog');
});*/
Route::get('/delete-skill','UserController@deleteSkill');
Route::post('/save-skill','UserController@saveSkill');
Route::post('/edit-skill','UserController@editSkill');
Route::get('clap/{id}','ClapController@Clap');
Route::get('/like','ClapController@ajaxClap');
Route::get('/unlike','ClapController@ajaxremoveClap');

Route::get('clapr/{id}','ClapController@removeClap');

Route::get('new-web-case', function(){
  return view('newwebdesign');
});
Route::get('new-ui-case', function(){
  return view('newuidesign');
});

Route::post('newuicase','newcaseController@storeui');
Route::get('new-seo-case', function(){
  return view('newposterdesign');
});
Route::get('new-seo-case/{id}','newcaseController@storeSeoClient');
Route::get('new-web-case/{id}','newcaseController@storeWebClient');
Route::get('new-ui-case/{id}','newcaseController@storeMobileClient');
Route::post('newpostercase','newcaseController@storeposter');
Route::post('newwebcase','newcaseController@storeweb');
Route::get('/', function () {
    return redirect('login');
});
Route::get('newcase',function(){
	return view('newcase');
});
Auth::routes();
Route::post('user_edit_pricing','UserController@add_pricing');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('newcase','newcaseController@store');
Route::resource('blog','BlogController');
Route::post('message','HomeController@sendMessage');
Route::resource('portofolio','PortofolioController');
Route::get('add-user',function(){
  return redirect()->route('users.create');
})->middleware('auth');
Route::resource('users','UserController');
Route::get('/oauth/github', 'AuthController@redirectToProvider');
Route::get('/oauth/github/callback', 'AuthController@handleProviderCallback');
Route::post('change_pic','AuthController@changePic');
Route::get('/savecookie','newcaseController@savecookie');

Route::get('/block-user','UserController@blockUser');
Route::get('/unblock-user','UserController@unblockUser');

resources/views/shared/box.blade.php
<div class="box">
		  <form>
		   <textarea class="form-control no-border" rows="3" placeholder="Type something..."></textarea>
		  </form>
		  <div class="box-footer clearfix">
		   <button class="btn btn-info pull-right btn-sm">Post</button>
		   <ul class="nav nav-pills nav-sm">
			<li class="nav-item"><a class="nav-link" href=""><i class="fa fa-camera text-muted"></i></a></li>
			<li class="nav-item"><a class="nav-link" href=""><i class="fa fa-video-camera text-muted"></i></a></li>
		   </ul>
		  </div>
</div>		

resources/views/shared/favblogs.blade.php
<div class="row" style="margin-top:2%;margin-bottom:10%;">
@foreach($favblogs as $blog)
          <div class="col-md-{{(count($blogs)==1)?12:4}} col-sm-{{(count($blogs)==1)?12:6}} portfolio-item" id="desc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <h6>{{(strlen($blog->title)>30)?mb_substr(strip_tags($blog->title),0,30).'..':$blog->title}}</h6>
              <p class="text-muted">{{(strlen($blog->subtitle))?mb_substr(strip_tags($blog->subtitle),0,60).'..':$blog->subtitle}}</p>
              <p>
                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>
              <p>
               @if(Auth::check() && Auth::user()->id==$blog->user_id)
                 <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <i class="fa fa-clock-o">
                  
               </i>
              {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
@if(isset($asc_blogs))
@foreach($asc_blogs as $blog)
          <div style="display:none;" class="col-md-{{(count($asc_blogs)==1)?12:4}} col-sm-{{(count($asc_blogs)==1)?12:6}} portfolio-item" id="asc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>{{mb_substr(strip_tags($blog->title),0,20)}}...</h4>
              <p class="text-muted">{{mb_substr(strip_tags($blog->subtitle),0,60)}}...</p>
              <p>
                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>
              <p>
                @if(Auth::check() && Auth::user()->id==$blog->user_id)
                 <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <i class="fa fa-clock-o" ></i>
                
                  
                </i>
                {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
@endif
@if(Auth::check()&& isset($user) && Auth::user()->id==$user->id && isset($unpublishedBlogs))

@foreach($unpublishedBlogs as $blog)
          <div  class="col-md-{{(count($unpublishedBlogs)==1)?12:4}} col-sm-{{(count($unpublishedBlogs)==1)?12:6}} portfolio-item" id="asc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              @if(count($blogs)<=2)
              <h4>{{mb_substr(strip_tags($blog->title),0,10)}}...</h4>
              @else
              <h4>{{mb_substr(strip_tags($blog->title),0,20)}}...</h4>
              @endif
              <p class="text-muted">{{mb_substr(strip_tags($blog->subtitle),0,60)}}...</p>
              <p>

                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>

              <p>
                <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                <i class="fa fa-lock" style="color:red;"></i>
                <i class="fa fa-clock-o">
                  
                </i>
                {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
@endif
@if(count($blogs)>6)
<div style="text-align:center;">
    <a href="{{url('portofolio')}}" class="btn btn-primary">{{trans('app.see_more')}}</a>
</div>
@endif
</div>

resources/views/shared/feed.blade.php
 <?php $class=''; ?>
 
@if(isset($blogs))
 @foreach($blogs as $blog)
 <?php $comment_count=App\Comments::where('blog_id',$blog->id)->count(); ?>
 <?php 
  $checkIfBlocked=App\BlockedUser::where('blocked_id',Auth::user()->id)->where('user_id',$blog->user_id)->count();
  $checkIfBlocked2=App\BlockedUser::where('blocked_id',$blog->user_id)->where('user_id',Auth::user()->id)->count();
  ?>
  @if($checkIfBlocked==0 && $checkIfBlocked2==0)
 <div class="tr-section feed">
		  <div class="tr-post">
		  	<a href="{{route('blog.show',['slug'=>$blog->slug])}}">
		   <div class="entry-header">
		    <div class="entry-thumbnail">
		     <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="Image">
		    </div><!-- /entry-thumbnail -->
	       </div><!-- /entry-header -->
	       </a>
		   <div class="post-content">
		    <div class="author-post">
		     <a href="{{route('users.show',$blog->username)}}"><img class="img-fluid rounded-circle" src="{{asset('img/users/'.$blog->userimage)}}" alt="Image"></a>
		    </div><!-- /author -->
		    <div class="entry-meta">
		     <ul>
			  <li><a href="#">{{$blog->postername}}</a></li>
			  <li>{{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</li>
			  <li><i class="fa fa-align-left"></i>&nbsp;{{rand(3,10)}} {{__('app.min_read')}}</li>
			  @if($blog->status==0)
			  <li><i  class="fa fa-lock"></i>&nbsp; {{__('app.private')}}<</li>

			  @endif
			  @if($blog->user_id==Auth::user()->id)
			  <li><a  href="{{route('blog.edit',$blog->slug)}}">
			  	<i  class="fa fa-pencil"></i></a>&nbsp;
			  </li>
			  <li><a id="deletebtn" onclick="deleteFunction('{{$blog->id}}')">
			  	<i  class="fa fa-trash"></i>
			     </a>&nbsp;
			  </a>
			  </li>
			  <form style="display:none;" id="deleteform_{{$blog->id}}" action="{{route('blog.destroy',[$blog->id])}}" method="POST">
               @method('DELETE')
               @csrf  
          </form>
			  @endif
		     </ul>
			</div><!-- /.entry-meta -->
			<h2><a href="{{route('blog.show',['slug'=>$blog->slug])}}" class="entry-title">{{$blog->title}}</a></h2>
			<p>{{$blog->subtitle}}</p>
			<div class="read-more">
		     <div class="feed pull-left">
			  <ul>
			  <li><i class="fa fa-comments"></i>{{$comment_count}}</li>&nbsp;
			  
			  <li>@include('shared.clap')</li>
			  </ul>	
		     </div><!-- /feed -->
			 <div class="continue-reading pull-right">
			  <a href="{{route('blog.show',['slug'=>$blog->slug])}}">Continue Reading <i class="fa fa-angle-right"></i></a>
			 </div><!-- /continue-reading -->
			</div><!-- /read-more -->											
		   </div><!-- /.post-content -->									
		  </div><!-- /.tr-post -->	
 </div><!-- /.tr-post -->
 @endif
@endforeach
@endif	

@if(count($blogs)==0)
<div class="alert alert-danger col-sm-12 text-center">{{__('app.no_blog_post')}}</div>
@endif
 	 

resources/views/shared/followers2.blade.php
<section class="posts-2 followers">
	  <div class="container">
	   <div class="row">
	    <div class="col-lg-12">

		<ul class="nav nav-tabs" role="tablist" id="myTabs">
		  <li class="nav-item">
			<a class="nav-link {{(count($followers)>0)?'active':''}}" href="#followers" role="tab" data-toggle="tab">{{__('app.followers')}}</a>
		  </li>
		  <li class="nav-item">
			<a id="followinga" class="nav-link " href="#following" role="tab" data-toggle="tab">{{__('app.followings')}}</a>
		  </li>
		</ul>
		<br></br>
 
		<!-- Tab panes -->
		<div class="tab-content">
		  <div role="tabpanel" class="tab-pane active" id="followers">
            @foreach($followers as $follower)
           <div class="card card-profile">
              <div class="card-block">
                <div class="media">
                  <div class="media-left">
                    <a href="#">
                      <img class="media-object rounded-circle" src="{{asset('img/users/'.$follower->image)}}" alt="">
                    </a>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading">
                      <a href="{{route('users.show',$follower->username)}}">{{$follower->name}}
                      </a>
                      </h4>
                    <p class="media-usermeta"><i class="fa fa-briefcase"></i> {{$follower->company}}</p>
                  </div>
                </div><!-- media -->
                @if($user->id==Auth::user()->id)
                <ul class="card-options">
                  <li><a class="dropdown-toggle" href="" data-toggle="dropdown" title="" data-original-title="View Options" id="dropdownMenuButton_{{$follower->id}}" role="button">
				            <i class="fa fa-ellipsis-v"></i>
				           </a>
                   <?php $checkIfFollowing=App\Followers::where('user_id',$follower->id)->where('follower_id',Auth::user()->id)->count(); ?>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton_{{$follower->id}}">
                    <a class="dropdown-item" href="#">{{__('app.block')}}</a>
                    @if($checkIfFollowing==0)
                    <a class="dropdown-item" onclick="followUser('{{$follower->id}}')">{{__('app.follow')}}</a>
                    @endif
                    
                  </div>
                 </li>
                </ul>
                @endif

              <div class="people-info">
                <div class="row">
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.location')}}</label>
                      {{$follower->location}}
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.email')}}</label>
                      {{$follower->email}}
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.website')}}</label>
                      {{$follower->website}}
                    </div>
                  </div>
                </div><!-- row -->
                <div class="row">
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.followers')}}</label>
                      <h4>{{$follower->followerscount}}</h4>
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.followings')}}</label>
                      <h4>{{$follower->followingscount}}</h4>
                    </div>
                  </div>
                  <div class="col-sm-4">
                  </div>
                </div><!-- row -->
              </div><!-- panel-info -->
              </div><!-- card-block -->
            </div><!-- card -->	
             @endforeach

           			
		  
		  </div><!-- tabpanel -->
		  <div role="tabpanel" class="tab-pane fade" id="following">
		   @foreach($followings as $following)

                    <?php 
                      $checkIfBlocked=App\BlockedUser::where('blocked_id',$following->id)->where('user_id',Auth::user()->id)->count();
                      ?>
            <div class="card card-profile">
              <div class="card-block">
                <div class="media">
                  <div class="media-left">
                    <a href="#">
                      <img class="media-object rounded-circle" src="{{asset('img/users/'.$following->image)}}" alt="">
                    </a>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading">
                      <a href="{{route('users.show',$following->username)}}">{{$following->name}}</a>
                       @if(Auth::user()->id==$user->id && $checkIfBlocked>0)
                          <i style="color:red" class="fa fa-ban" id="realblockicon_{{$following->id}}" title="blocked user">
                            
                          </i>
                       @endif
                       <i class="fa fa-ban" id="followinblockedicon_{{$following->id}}" style="display:none;">
                            
                       </i>
                      </h4>
                    <p class="media-usermeta"><i class="fa fa-briefcase"></i> {{$following->company}}</p>
                  </div>
                </div><!-- media -->
                @if($user->id==Auth::user()->id)
                <ul class="card-options">
                  <li><a class="dropdown-toggle" href="" data-toggle="dropdown" title="" data-original-title="View Options" id="followingdropdownMenuButton_{{$following->id}}" role="button">
                    <i class="fa fa-ellipsis-v"></i>
                   </a>
                   
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="followingdropdownMenuButton_{{$following->id}}">
                    @if($checkIfBlocked>0)
                    <a class="dropdown-item" id="realunblocka_{{$following->id}}" onclick="unblockUser('{{$following->id}}')">{{__('app.unblock')}}</a>
                    <a style="display:none;" id="blocka_{{$following->id}}" class="dropdown-item" onclick="blockUser('{{$following->id}}')">{{__('app.block')}}</a>
                   @else
                   <a class="dropdown-item" id="realblocka_{{$following->id}}" onclick="blockUser('{{$following->id}}')">{{__('app.block')}}</a>
                   <a style="display:none;" id="unblocka_{{$following->id}}" class="dropdown-item" onclick="unblockUser('{{$following->id}}')">{{__('app.unblock')}}</a>
                   @endif
                    
                  </div>
                 </li>
                </ul>
                @endif

              <div class="people-info">
                <div class="row">
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.location')}}</label>
                      {{$following->location}}
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>Email</label>
                      {{$following->email}}
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.website')}}</label>
                      {{$following->website}}
                    </div>
                  </div>
                </div><!-- row -->
                <div class="row">
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.followers')}}</label>
                      <h4>{{$following->followerscount}}</h4>
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="info-group">
                      <label>{{__('app.followings')}}</label>
                      <h4>{{$following->followingscount}}</h4>
                    </div>
                  </div>
                  <div class="col-sm-4">
                  </div>
                </div><!-- row -->
              </div><!-- panel-info -->
              </div><!-- card-block -->
            </div><!-- card --> 
		  @endforeach
		  </div><!-- tabpanel -->
		</div>	   
	   
	    </div>
	   </div><!--/ row -->
	  </div><!--/ container -->
    </section><!--/ section -->		
    <script type="text/javascript">
      window.onload=function(){

        @if(count($followers)==0)
        
          $("#followinga").click()
        @endif
      }
    </script>

resources/views/shared/followings.blade.php
<div class="col-sm-12" style="margin-bottom:4%;">
    
    <input class="col-xs-12" style="margin-bottom:3%;width:80%; display: inline-block;" class="inline" onkeyup="Mysort3();"  type="text" name="" id="mysearch3" placeholder="{{trans('app.enter_username')}}">
 
</div>
<div id="list3" style="">
@foreach($followings as $user)
<div class="container" id="desc">
    <div class="card flex-row flex-wrap">
        <div class="card-header border-0">
            <img class="profileimage" src="{{asset('img/users/'.$user->image)}}" alt="">
            <span>
                    @if(Auth::check())

                    <?php 
                     $checkIfFollow=App\Followers::where('follower_id',Auth::user()->id)->where('user_id',$user->id)->count();
                     $checkIfFollowing=App\Followers::where('user_id',Auth::user()->id)->where('follower_id',$user->id)->count();
                    ?>
                      
                      @if($user->id!=Auth::user()->id)
                          @if($checkIfFollow==0)
                      
                    <a style="margin-left:2%;" href="{{url('follow/'.$user->id)}}" class="badge badge-dark pull-right">
                        <i class="fa fa-plus">
                            
                        </i>
                        {{__('app.follow')}}
                    </a>
                          @else
                        <a style="margin-left:2%;"class="badge badge-success pull-right">
                        
                        {{__('app.following')}}
                       </a>

                          @endif
                       @endif
                        @if($checkIfFollowing && $user->id!=Auth::user()->id)
                       {{__('app.is_following_you')}}
                       @endif
                    @else
                    <a style="margin-left:2%;" href="{{url('follow/'.$user->id)}}" class="badge badge-dark pull-right">
                        <i class="fa fa-plus">
                            
                        </i>
                        {{__('app.follow')}}
                    </a>

                      
                    @endif
                </span>
        </div>
        <div class="card-block px-2">
            
                <h4 class="card-title">
                <span>
                    {{$user->name}} 
                </span>
                
               
               </h4>
            
            
            <span class="text-muted">{{trans('app.worked_at')}}: {{$user->company}}</span>
            <p class="card-text">{{mb_substr(strip_tags($user->description),0,100)}}...</p>
            <p class="card-text">
                {{(isset($user->experience))?$user->experience:''}} {{trans('app.years_experience')}}
            </p>
            <p>
                
                <?php $skills=explode(",",$user->skills);
                 
                 ?>
                @if(count($skills)>1)
                <h6>{{trans('app.skills')}}</h6>
                @foreach($skills as $skill)
                <a href="#" class="badge badge-dark badge-pill">{{$skill}}
                </a>
                @endforeach

                @else
                <h6>{{trans('app.no_skills-earned_yet')}}</h6>
                @endif

            </p>
            <p>
                <i class="fa fa-map-marker">
                    {{$user->location}}
                </i>
            </p>
            <a  href="{{route('users.show',$user->username)}}" class="btn btn-info">{{trans('app.view_user')}}</a>
            <br><br>
          </div>

        <div class="w-100"></div>
        <div class="card-footer w-100 text-muted">
            {{trans('app.joined').'  '.(new Carbon\Carbon($user->created_at))->diffForHumans()}}
        </div>
    </div>
    <br>
</div>
@endforeach
</div>

<script type="text/javascript">
    function Mysort3() {
    // Declare variables
    var input, filter, listDiv, span, h4, i;
    input = document.getElementById('mysearch3');
    filter = input.value.toUpperCase();
    listDiv = document.getElementById("list3");
    h4 = listDiv.getElementsByTagName('h4');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < h4.length; i++) {
        span = h4[i].getElementsByTagName("span")[0];
        var parentDiv=h4[i].parentNode.parentNode.parentNode;
        if (span.innerHTML.toUpperCase().indexOf(filter) > -1) {
            parentDiv.style.display = "";
        } else {
            parentDiv.style.display = "none";
        }
    }
}
</script>

resources/views/shared/mutuals.blade.php
@if(count($mutuals)>0)
<section class="box-typical">
			<header class="box-typical-header-sm">People you may know</header>
			<div class="people-rel-list">
				<ul class="people-rel-list-photos">
					@foreach($mutuals as $mutual)
					 	@if($mutual['id']!=Auth::user()->id)
					<li><a href="{{route('users.show',$mutual['username'])}}"><img src="{{asset('img/users/'.$mutual['image'])}}" alt="{{$mutual['name']}}" title="{{$mutual['name']}}"></a></li>
					    @endif
					@endforeach
					
				</ul>
				<form class="site-header-search" action="{{url('users-search')}}" method="get">
					{{csrf_field()}}
					<input placeholder="Search for people" type="text" name="keyword">
					<button type="submit">
						<span class="fa fa-search"></span>
					</button>
					<div class="overlay"></div>
				</form>
			</div>
		</section>	
@endif

resources/views/shared/readers.blade.php
<style type="text/css">
    .loader {
  border: 1px solid #f3f3f3; /* Light grey */
  border-top: 1px solid #3498db; /* Blue */
  border-radius: 50%;
  width: 15px;
  height: 15px;
  animation: spin 2s linear infinite;
  display:none;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
<div id="list" style="">
@foreach($readers as $reader)
<div class="container" id="user_{{$reader->id}}"style="height:140px;">
    <div class="card flex-row flex-wrap">
        
        <div class="card-header border-0" style="display:inline-block;">

            <a href="{{route('users.show',$reader->username)}}">
            <div style="margin-bottom:4%;">
                <img height="50" width="50" class="thumb-lg img-circle" src="{{asset('img/users/'.$reader->image)}}" alt="profile image">
            </div>
            </a>
            <div class="col-sm-12" style="text-align:center;">
               
            </div>
            
        </div>
        <div class="card-block px-2">
            
            
                <h4 class="card-title">
                <span style="display:inline-block;">
                    <a href="{{route('users.show',$reader->username)}}">{{$reader->name}}

                    </a>
                    <small style="margin-right:2%;">
                        ({{__('app.reads')}} {{$reader->read_count}} {{__('app.times')}})
                    </small>
                    
                </span>
                 @include('shared.follow_btn')
                
               </h4>
          </div>

        <div class="w-100"></div>
        <div class="card-footer w-100 text-muted">
            {{trans('app.joined').'  '.(new Carbon\Carbon($reader->created_at))->diffForHumans()}}
        </div>
    </div>
    
</div>
@endforeach
</div>

<script type="text/javascript">

    
    function Mysort() {
    // Declare variables
    var input, filter, listDiv, span, h4, i;
    input = document.getElementById('mysearch');
    filter = input.value.toUpperCase();
    listDiv = document.getElementById("list");
    h4 = listDiv.getElementsByTagName('h4');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < h4.length; i++) {
        span = h4[i].getElementsByTagName("span")[0];
        var parentDiv=h4[i].parentNode.parentNode.parentNode;
        if (span.innerHTML.toUpperCase().indexOf(filter) > -1) {
            parentDiv.style.display = "";
        } else {
            parentDiv.style.display = "none";
        }
    }
}
</script>

resources/views/shared/search_form.blade.php
<form class="col-sm-12" method="post" action="{{url('blog-search')}}">
	{{csrf_field()}}
	
	<div class="form-group col-sm-12">
			<input type="text" name="keyword" class="form-control" placeholder="{{__('app.type_keword_to_search')}}">
	</div>
	
	<div class="form-group col-sm-3 pull-right">
			<button style="width:100%;" type="submit" class="btn btn-primary ">
				{{__('app.search')}}
	 		</button>
	</div>
</form>