routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/readerajaxfollow','FollowerController@ajaxfollow');
Route::get('/readerajaxunfollow','FollowerController@ajaxunfollow');
Route::post('/savetime','UserController@saveTime');
Route::get('ajaxfollow','FollowerController@ajaxfollow');
Route::get('ajaxunfollow','FollowerController@ajaxunfollow');
Route::get('users-search','UserController@search');
Route::resource('groups','GroupController');
Route::get('blogs/{cat}','BlogController@view_by_category');
Route::get('followers/{username}','UserController@followers');

Route::post('comment-reply','CommentController@reply');
Route::resource('comment','CommentController');
Route::post('/payment/process', 'PaymentController@process')->name('payment.process');
Route::get('all-notification','FollowerController@all_notifications');
Route::get('readNotification','FollowerController@readNotification');

Route::get('follow/{user_id}','FollowerController@add');
Route::get('unfollow/{user_id}','FollowerController@unfollow');

Route::get('/callback','ApiController@getData')
;
Route::get('blog-search','BlogController@search');

Route::post('add-rating','FollowerController@add_rating');

Route::get('/AuthCallback','ApiController@grantAccess');

Route::get('/redirect', function () {
    $query = http_build_query([
        'client_id' => '4',
        'redirect_uri' => 'http://africanfreelancers.net/AuthCallback',
        'response_type' => 'code',
        'scope' => '*',
    ]);

    return redirect('https://www.opendarasa.com/oauth/authorize?'.$query);
});
Route::get('get-talents','ApiController@getTalents');
Route::get('services',function(){
  return view('services');
});
Route::get('language/{lang}','HomeController@changeLanguage');
Route::post('add_skills','UserController@addSkills');
Route::get('publishBlog/{slug}','HomeController@publishBlog');
Route::get('publishWork/{slug}','HomeController@publishWork');
Route::get('unpublishWork/{slug}','HomeController@unpublishWork');
Route::get('unpublishBlog/{slug}','HomeController@unpublishBlog');
Route::post('profile-type','HomeController@saveprofile');
/*Route::get('portofolio',function(){
  return view('portofolio');
});
Route::get('blog',function(){
   return view('blog');
});*/
Route::get('/delete-skill','UserController@deleteSkill');
Route::post('/save-skill','UserController@saveSkill');
Route::post('/edit-skill','UserController@editSkill');
Route::get('clap/{id}','ClapController@Clap');
Route::get('/like','ClapController@ajaxClap');
Route::get('/unlike','ClapController@ajaxremoveClap');

Route::get('clapr/{id}','ClapController@removeClap');

Route::get('new-web-case', function(){
  return view('newwebdesign');
});
Route::get('new-ui-case', function(){
  return view('newuidesign');
});

Route::post('newuicase','newcaseController@storeui');
Route::get('new-seo-case', function(){
  return view('newposterdesign');
});
Route::get('new-seo-case/{id}','newcaseController@storeSeoClient');
Route::get('new-web-case/{id}','newcaseController@storeWebClient');
Route::get('new-ui-case/{id}','newcaseController@storeMobileClient');
Route::post('newpostercase','newcaseController@storeposter');
Route::post('newwebcase','newcaseController@storeweb');
Route::get('/', function () {
    return redirect('login');
});
Route::get('newcase',function(){
	return view('newcase');
});
Auth::routes();
Route::post('user_edit_pricing','UserController@add_pricing');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('newcase','newcaseController@store');
Route::resource('blog','BlogController');
Route::post('message','HomeController@sendMessage');
Route::resource('portofolio','PortofolioController');
Route::get('add-user',function(){
  return redirect()->route('users.create');
})->middleware('auth');
Route::resource('users','UserController');
Route::get('/oauth/github', 'AuthController@redirectToProvider');
Route::get('/oauth/github/callback', 'AuthController@handleProviderCallback');
Route::post('change_pic','AuthController@changePic');
Route::get('/savecookie','newcaseController@savecookie');

Route::get('/block-user','UserController@blockUser');
Route::get('/unblock-user','UserController@unblockUser');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/blog_css.blade.php
<style>

/* Header/Blog Title */
.header {
    padding: 30px;
    font-size: 40px;
    text-align: center;
    background: white;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {   
    float: left;
    width: 75%;
}

/* Right column */
.rightcolumn {
    float: left;
    width: 25%;
    padding-left: 20px;
}

/* Fake image */
.fakeimg {
    background-color: #f7fdff;
    width: 100%;
    padding: 20px;
}

/* Add a card effect for articles */
.card {
     background-color: white;
     padding: 20px;
     margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}
.sidebarimg{
    height:70px;
    width:100%;
}
.blogmainimg{
    width:100%;
    height:100%;
}


/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {   
        width: 100%;
        padding: 0;
    }
}
</style>

resources/views/layouts/category.blade.php
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1">
  @include('layouts.head2')
  <body>
  
     @include('layouts.nav2')

    @include('shared.posts')
	 
	@include('shared.readmore') 
	
     @include('layouts.footer2')
    @include('layouts.js2')

  </body>
</html>

resources/views/layouts/comments.blade.php
 <?php
 $divid=Session::get('divid');
  ?>
 <!-- ==============================================
	 Post Content
	 =============================================== -->
     <article class="post-comments">
      <div class="container">
       <div class="row">
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
		
		  <div class="comments-list-notification">
		   <h4><span class="text">{{count($comments)}} {{__('app.comments')}}</span></h4>
		  </div><!-- /.comment-list -->
		   <div class="comments-list">
			<!-- The contactform -->
			<form action="{{route('comment.store')}}" method="post" name="contactform" id="contactform">
				{{csrf_field()}}
			 <fieldset>
			   <!-- Comments / Message -->
			   <label for="comments" accesskey="C"><i class="fa fa-comment"></i></label>
			   <textarea name="comment" id="comment"></textarea>
			   <!-- Send button -->
			   <input type="hidden" name="blog_id" value="{{$blog->id}}">
			   <div class="text-center">
			   <button  type="submit" class="kafe-btn kafe-btn-mint full-width">{{__('app.comment')}}</button>
			   </div>
			 </fieldset>
			</form>	
		  </div><!-- /.comment-list -->	
		@foreach($comments as $comment)
		  <div class="comments-list" id="mycomment_{{$comment->id}}">
			
			 <div class="comment-body">
			  <div class="author-avatar">
			   <img alt="..." src="{{asset('img/users/'.$comment->image)}}" class="img-fluid" width="100" height="100">        
			  </div>
			  <div class="comment-content">
				<span class="author-name">{{$comment->name}}</span>                
				<span class="author-time">{{(new Carbon\Carbon($comment->created_at))->diffForHumans()}}</span>
				<p class="author-post">{{$comment->comment}}</p>
				<a rel="nofollow" class="comment-reply-link"  aria-label="Reply to Bablofil" id="" onclick="showReplyForm('{{$comment->id}}')">Reply</a>
				<a style="display:none;display:" rel="nofollow" class="comment-reply-link"  aria-label="Reply to Bablofil" id="cancel_{{$comment->id}}" onclick="cancelReplyForm('{{$comment->id}}')">cancel</a>
					   <!--- reply form-->
			  <div id="replyform_{{$comment->id}}" class="comments-list" style="display:none;margin-top:4%;">
			<!-- The contactform -->
			<form  action="{{url('comment-reply')}}" method="post" name="contactform" id="contactform_{{$comment->id}}">
				{{csrf_field()}}
			 <fieldset>
			   <!-- Comments / Message -->
			   
			   <textarea class="form-control" name="comment" id="comment" placeholder="{{__('app.leave_a_reply')}}"></textarea>
			   <!-- Send button -->
			   <input type="hidden" name="comment_id" value="{{$comment->id}}">
			   <div class="text-center">
			   <button onclick="submitReply('{{$comment->id}}')" type="button" class="kafe-btn kafe-btn-mint full-width">{{__('app.reply')}}</button>
			   </div>
			 </fieldset>
			</form>	
		  </div><!-- /.reply form -->
				<?php

				$replies=json_decode("[".$comment->replies."]");
				$limit=1;
				 ?>
				 @if($replies!=null)

				  <hr>
			
				  <span>{{count($replies)}} {{__('app.replies')}}</span>
				  @if(count($replies)>6)
				  <span style="float:right;"><a  id="showbtn_{{$comment->id}}" value="show more"  onclick="showMore('{{$comment->id}}')">show more</a></span>
				  @endif
				  <input type="hidden" value="{{count($replies)}}" name="" id="total">
				  @foreach($replies as $reply)
				  <?php $limit++; ?>

				 <div id="reply_{{$limit}}_{{$comment->id}}" class="replies" style="margin-top:4%;display:{{($limit<6)?'block':'none'}}">
				  <div class="author-avatar" style="width:50px;height:50px;">
				   <img alt="..." src="{{asset('img/users/'.$reply->image)}}" class="img-fluid" width="50" height="50">        
				  </div>
					<div class="comment-content" >
					<span class="author-name">{{$reply->name}}</span>                
					<span class="author-time">{{(new Carbon\Carbon($reply->created_at))->diffForHumans()}}</span>
					<p class="author-post">{{$reply->comment}}</p>
					 
				       </div><!-- /.comment-content -->
				 </div>
				 <br>

				 @endforeach
				 @endif 
			  </div><!-- /.comment-content -->
			 </div><!-- .comment-body -->

				 
		  </div><!-- /.comment-list -->
		    
		
		  @endforeach
		
		  	
		
		   
		
        </div><!-- /col-lg-8 -->
       </div><!-- /row -->
      </div><!-- /container -->
     </article><!-- /article -->

     <script type="text/javascript">
     	window.onload=function(){
     		@if(isset($divid))
     			window.location="{{Request::url()}}#{{$divid}}"
     		@endif
     	}
     	
     	function showReplyForm(id) {
     		
     		$("#replyform_"+id).css({display:'block'});
     		$("#cancel_"+id).css({display:'inline-block'});

     	}

     	function cancelReplyForm(id) {
     		$("#replyform_"+id).css({display:'none'});
     		$("#cancel_"+id).css({display:'none'});
     	}
     	function submitReply(id){
     		$("#contactform_"+id).submit();
     	}

     	function showMore(id) {
     		var total=$("#total").val();
              //console.log(total);
              var option=$("#showbtn_"+id).html();
             if(option=='show more')
             {
             	for (var i = 1; i < total+1; i++) {
     			
     				$("#reply_"+i+"_"+id).css({display:'block'});
     			
     		    }
     		    $("#showbtn_"+id).html('show less');
             }else{
             	for (var i =6; i < total+1; i++) {
     			
     				$("#reply_"+i+"_"+id).css({display:'none'});
     			
     		  }
     		  $("#showbtn_"+id).html('show more');
             }
     		
     	}
     </script>

resources/views/layouts/fileinput.blade.php
<!-- Bootstrap core JavaScript -->
    <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
    <!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
    wish to resize images before upload. This must be loaded before fileinput.min.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/piexif.min.js" type="text/javascript"></script>
<!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview. 
    This must be loaded before fileinput.min.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/sortable.min.js" type="text/javascript"></script>
<!-- purify.min.js is only needed if you wish to purify HTML content in your preview for 
    HTML files. This must be loaded before fileinput.min.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/purify.min.js" type="text/javascript"></script>
<!-- popper.min.js below is needed if you use bootstrap 4.x. You can also use the bootstrap js 
   3.3.x versions without popper.min.js. -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/fileinput.min.js"></script>
<!-- optionally uncomment line below for loading your theme assets for a theme like Font Awesome (`fa`) -->
<!-- script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/themes/fa/theme.min.js"></script -->
<!-- optionally if you need translation for your language then include  locale file as mentioned below -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/locales/LANG.js"></script>

resources/views/layouts/footer2.blade.php
 <style type="text/css">
 	.bottom-footer{
 		bottom:0;
 		right:0;
 		left:0;
 		z-index:2;
 		position:fixed;
 	}
 	@media screen and (max-width: 1000px){
 		.bottom-footer{
 			margin-top:550px;
 			position:fixed;
 		}
 	}
 </style>
 <!-- ==============================================
     Footer Section
     =============================================== -->	
     <footer class="bottom-footer" >
	  <div class="container">
	   <p><span>©{{date('Y')}} {{config('app.name')}}</span></p>			
		 
	   <ul id="menu-footer-menu">
	    <li>
	     <a href="#">Privacy</a>
	    </li><!-- /li -->
		<li>
		 <a href="#">Terms & Conditions</a>
		</li><!-- /li -->
		
	   </ul><!-- /ul -->	
	   
	  </div><!-- /container -->
     </footer><!-- /footer -->
     <a id="scrollup">Scroll</a>

resources/views/layouts/head.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="pDSfOJVqhmtTVfbYdXEmn0ykGNzV5ry1-yYh_YBU9YM" />

    @yield('meta')
    <!-- Bootstrap core CSS -->
    <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{asset('css/carousel.css')}}">
    <!-- Custom fonts for this template -->
    <link href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
  
    <!-- Custom styles for this template -->
    <link href="{{asset('css/agency.min.css')}}" rel="stylesheet">
    <!-- dependency: React.js -->
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap2-toggle.min.css" rel="stylesheet">

    <script src="http://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125384289-1"></script>
<script src="https://js.braintreegateway.com/web/dropin/1.8.1/js/dropin.min.js"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125384289-1');


</script>





    <!-- Literally Canvas -->
    
  <style type="text/css">
    .carouselImage{
      width: 90px; 
      height: 90px; 
    margin: 0 auto;
    border-radius: 50%;
    border: 1px solid #5db4c0;
    margin-top:2%;
    margin-bottom:0%;
    }
    .mystudies {
      margin-bottom:5%;
      
    }
    .myskills{
      margin-bottom:5%;
      margin-top: 5%;
    }
    .profileimage{
    width:150px;
    height: 150px;
}
.container{
    margin-top:0%;
}
a.notif {
  position: relative;
  display: block;
  height: 50px;
  width: 50px;
  background: url('http://i.imgur.com/evpC48G.png');
  background-size: contain;
  text-decoration: none;
}
.num {
  position: absolute;
  right: 11px;
  top: 6px;
  color: #fff;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #f1f1f1}

/* Show the dropdown menu on hover */
.num:hover .dropdown-content {
  display: block;
}

.ui-corner-all {
  left:16px;
  width:200px;
  background:gray;
  text-align:center;
  border-radius: 4px;
  color:white;
  display:inline-block;
  top:-2 !important;
}




  </style>
  

resources/views/layouts/head2.blade.php
<head>

	
	    <!-- ==============================================
		Title and Meta Tags
		=============================================== -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		
		 @yield('meta')
		
		<!-- ==============================================
		Favicons
		=============================================== --> 
		<link rel="shortcut icon" href="{{asset('Medium/img/favicons/favicon.ico')}}">
		<link rel="apple-touch-icon" href="{{asset('Medium/img/favicons/apple-touch-icon.png')}}">
		<link rel="apple-touch-icon" sizes="72x72" href="{{asset('Medium/img/favicons/apple-touch-icon-72x72.png')}}">
		<link rel="apple-touch-icon" sizes="114x114" href="{{asset('Medium/img/favicons/apple-touch-icon-114x114.png')}}">
		
	    <!-- ==============================================
		CSS
		=============================================== -->
        <!-- Style-->
        
        
        
        <link type="text/css" href="{{asset('Medium/bower_components/bootstrap/dist/css/bootstrap.css')}}" rel="stylesheet" />
        
        <link type="text/css" href="{{asset('Medium/css/app.css')}}" rel="stylesheet" />
        <!-- dependency: React.js -->
		<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
		
		
				
		<!-- ==============================================
		Feauture Detection
		=============================================== -->
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="{{asset('Medium/js/modernizr-custom.js')}}"></script>

		

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

		<style type="text/css">
			.popover-content{
				display:none;
			}
			.note-toolbar a{
				color: black;
			}
			.loader {
  border: 1px solid #f3f3f3; /* Light grey */
  border-top: 1px solid #3498db; /* Blue */
  border-radius: 50%;
  width: 15px;
  height: 15px;
  animation: spin 2s linear infinite;
  display:none;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.skill :hover{
 display:block;
}
#editskill{
display:none;
}
		</style>	
		
  </head>

resources/views/layouts/newcase_head.blade.php
<head>

    @include('layouts.head')
<!-- dependency: React.js -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />

  <style type="text/css">

* {
  box-sizing: border-box;
}

body {
  background-color: #f1f1f1;
}

#regForm {
  background-color: #ffffff;
  margin: 100px auto;
  font-family: Raleway;
  padding: 40px;
  width: 70%;
  min-width: 300px;
}

h1 {
  text-align: center;  
}

input {
  padding: 10px;
  width: 100%;
  font-size: 17px;
  font-family: Raleway;
  border: 1px solid #aaaaaa;
}

/* Mark input boxes that gets an error on validation: */
input.invalid {
  background-color: #ffdddd;
}

/* Hide all steps by default: */
.tab {
  display: none;
}

button {
  background-color: #4CAF50;
  color: #ffffff;
  border: none;
  padding: 10px 20px;
  font-size: 17px;
  font-family: Raleway;
  cursor: pointer;
}

button:hover {
  opacity: 0.8;
}

#prevBtn {
  background-color: #bbbbbb;
}

/* Make circles that indicate the steps of the form: */
.step {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbbbbb;
  border: none;  
  border-radius: 50%;
  display: inline-block;
  opacity: 0.5;
}

.step.active {
  opacity: 1;
}

/* Mark the steps that are finished and valid: */
.step.finish {
  background-color: #4CAF50;
}
canvas{
  height: 700px;
  width: 700px;
}
.btn-sm
{
  display:block;
  background-color:#777e89;
}
.popover-content {
  display: none;
}
.profileimage{
  width:150px;
  height: 150px;
}
.share,
.facebook,
.google-plus,
.linkedin,
.twitter
{
  display:inline-block;
  margin-left:20px;
}
  </style>
  </head>

resources/views/layouts/newsfeed.blade.php
<!DOCTYPE html>
<html lang="en">
 
 @include('layouts.head2')
  <body>
  @include('layouts.nav2')
     

     <!-- ==============================================
     Posts Section
     =============================================== -->		  
	  
	 <section class="posts-2">
	  <div class="container-fluid">
	   <div class="row">

        @include('shared.panel')	  

        <div class="col-md-6"> 
		
	     @yield('postbox')
		
		 @yield('feed')
		 
		 
        </div><!-- /.col-md-6 -->	
		
        <div class="col-md-3"> 

		  @yield('mutuals')
		
	      @yield('ad')	
		
        </div><!-- /.col-md-3 -->	
	   
	   </div><!-- /.row -->
	  </div><!-- /.container -->
     </section><!-- /.section -->
	 
	 <!-- ==============================================
	 More Section
	 =============================================== -->		  
	@yield('readmore')
    @include('layouts.footer2')
	 
     
	 
    @include('layouts.js2')

  </body>
</html>